name = "Albanian"
version = "0.1.1"

[macos]
system_pkg_id = "no.divvun.MacDivvun.sq"

[windows]
system_product_code = "856B1B2F-CE1B-4743-BC7F-261923CE9F3D"
msoffice_product_code = "042AB625-F33D-4FAA-A503-A358FB484C27"
