[package]
name = "sqi"
human_name = "Albanian"
version = "0.1.0"

# Table of speller tag -> filename to include in the bundle
# filenames depends on specific project
[spellers.sqi]
filename = "sq-mobile.zhfst"

# Table of bundles to generated
# key is the type of bundle
# Windows speller bundle require a uuid for the installer
[bundles.speller_win]
package = "speller-sqi"
platform = "windows"
uuid = "856B1B2F-CE1B-4743-BC7F-261923CE9F3D"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_macos]
pkg_id = "no.divvun.MacDivvun.sq"
package = "speller-sqi"
platform = "macos"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_win_mso]
package = "speller-sqi-mso"
platform = "windows"
uuid = "042AB625-F33D-4FAA-A503-A358FB484C27"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_mobile]
package = "speller-sqi"
platform = "mobile"
repo = "https://pahkat.uit.no/main/"
